<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRsjbihd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRsjbihd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRsjbihd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRsjbihd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRsjbihd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rsjbihd',
    'container.build_id' => '8d62ce5c',
    'container.build_time' => 1551110586,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRsjbihd');
